### ISSUE TITLE
No window list shown in minimal configuration

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#19]
When a new user account is created, at least in Debian the user has only one active activity with only one virtual desktop. If WorkFlow is opened with this conditions on the Desktop, it does not show a list of open windows.

**Comment by psifidotos** [comment]
That's very interesting.. I must test it to see what's going on... Probably the windows do not have a value for desktop and activity in that case...

**Comment by psifidotos** [comment]
In my system these windows are shown like in Everywhere state... In Debian are not shown at all? Not even in the Everywhere Window area? (We can change that behavior, I dont know what is better in this step, probably the simpler right? to be shown in the WorkAreas and not in the Everywhere area in order to no confuse the user... )

**Comment by MagicMuscleMan** [comment]
You are right, they are shown in the everywhere area, at least with the most current version. I think they haven't been there when I reported the bug, but I am not sure about that and it does not matter.

I think putting them as normal windows in the window list would be a bit more logical/consistent, as they probably appear there when adding a second virtual desktop or a second activity, so the concept should be simpler to understand for new users starting with such a minimal configuration. But, of course, having them in the everywhere area is also technically correct.

So this is no "bug" anymore, but more of a low-priority whish.

**Comment by psifidotos** [comment]
I discovered that in this specific case the Windows are set on onAllActivities and onAllDesktops from KDE. This is why the windows are shown in the Everywhere panel. There is the situation that if we make them to be shown in the first Workarea we wouldnt be consistent with KDE. For example there would be an issue where the user adds a desktop or activity. In that case the windows in which state are they? Will the remain in Everywhere state? What did the user want? I think that this is KDE's choice actually...

**Comment by MagicMuscleMan** [comment]
I fully agree that you should stick to KDE's defaults here. If there is real user demand for a change, this should be discussed with KDE. I think the issue can be closed.
