### ISSUE TITLE
Dragging-and-dropping windows does not work

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#2]
A non-global window cannot be drag-and-dropped directly from one virtual desktop of an activity to another virtual desktop. It is possible to change the state of a window to "everywhere" and then drag-and-drop it to the choosen desktop, but doing it directly does not work. The direct solution would be more intuitive and faster.

**Comment by psifidotos** [comment]
This is important. It should work. Dragging in enabled for 3 states in windows.
1. -> To Desktop
2. -> To New Desktop
3. -> Everywhere

For 2, in my version also it does not work but for 1 we must research it...
Write down your system versions to see what's happening....
Operating System (?) - KDE version (?)

**Comment by MagicMuscleMan** [comment]
It's a Debian (testing) Linux 64-bit with KDE 4.8.4 with libx11-dev 1.5.0.

Unfortunately, I can't fully reproduce the behaviour, as 3. stopped working, too (1. and 2. never worked). I created a new user to have an empty profile, but there no window list appears at all, independet of switching the show/hide window button and independent of having the plasmoid on the desktop or on the dashboard

**Comment by psifidotos** [comment]
There is a chance that has been fixed in master now. Can you please test it?

**Comment by MagicMuscleMan** [comment]
I tested it, but although my other issue is resolved (so I know, that updating the version did work), dragging of windows still does not work for me.

Could it be a user problem? Maybe I give a step-by-step explanation what I am doing, so you can correct me if I am doing anything wrong.
1. I open the dashboard, where WorkFlow is added
2. I move the mouse to the first virtual desktop on the first active activity on a window name
3. The window name gets green and two buttons appear ("change window state" and "close window")
4. I (left) click on the green name (avoiding the buttons) and keep the mouse button pressed
5. I move the mouse, but nothing happens (the window name does not move, the cursor shape does not change, the cursor icon itself moves as if I hadn't clicked at all)
6. I move the mouse to another virtual desktop of the same activity (or to another activity, both tested) and release the mouse button
7. Still nothing happens

Can I create some debug data or logging data, which might help analysing the issue? I have some programming experience if that might help, although I am not familiar with QML.

**Comment by psifidotos** [comment]
After four next to the cursor the windows icon appears.
Lets try to make a small debuging. Do the following....

1.Open a command prompt
2.Run,    plasmoidviewer workflow (it opens the plasmoid in a window)
3.Try the dragging as you described above
4.In the command prompt what messages appear?

**Comment by MagicMuscleMan** [comment]
When opening the plasmoid I get the following message:
plasmoidviewer(16980)/kdecore (services) KServiceFactory::findServiceByDesktopPath: "" not found

I do get this message for other plasmoids, too, so I do not know if it is important.

When dragging, I do not get a message at all. When making the window smaller, I see that instead of moving the window name, the whole panel containing the active activities and virtual desktops is moved. Might it be, that this is a scroll pane absorbing all dragging events, which thus do not reach the window names?

By the way, when I change the window state, I get debug messages to the console, so in principle debugging seems to work:
setTaskState:71303236-allDesktops
setTaskState:71303236-allActivities
setTaskState:71303236-oneDesktop

**Comment by MagicMuscleMan** [comment]
As discussed yesterday on IRC, dragging does work, if the mouse is not moved after pressing for about two seconds. Afterwards, the mouse may be moved. This is the Qt implementation and pressing and releasing events should be used instead.

**Comment by MagicMuscleMan** [comment]
Your changed version is totally awesome. It's so fast and fluid that it is great fun arbitrarily moving windows around.

**Comment by MagicMuscleMan** [comment]
Due to fixing the freeze of the complete plasma environment (fd9965c), moving windows around has some delay again. With the following patch, the delay disappears and I cannot see any disadvantages:

```
--- a/src/package/contents/Activities2.qml
+++ b/src/package/contents/Activities2.qml
@@ -70,7 +70,7 @@ Rectangle {
     property int themePos:0

     property int toolTipsDelay:300
-    property int pressAndHoldInterval:120
+    property int pressAndHoldInterval:0
```

I didn't sent you a merge request, as we already talked about timer and I still think that they are not needed, but you seemed to have reasons why they were needed. What are the downsides of setting the timer to 0 as above (which is probably equivalent to removing the timer completely)?

**Comment by MagicMuscleMan** [comment]
Due to fixing the freeze of the complete plasma environment (fd9965c), moving windows around has some delay again. With the following patch, the delay disappears and I cannot see any disadvantages:

```
--- a/src/package/contents/Activities2.qml
+++ b/src/package/contents/Activities2.qml
@@ -70,7 +70,7 @@ Rectangle {
     property int themePos:0

     property int toolTipsDelay:300
-    property int pressAndHoldInterval:120
+    property int pressAndHoldInterval:0
```

I didn't sent you a merge request, as we already talked about timer and I still think that they are not needed, but you seemed to have reasons why they were needed. What are the downsides of setting the timer to 0 as above (which is probably equivalent to removing the timer completely)?

**Comment by psifidotos** [comment]
I think that with the merge that  I have just uploaded all this mess with dragging must have been fixed.
Let me tell you a small story:). Timer was needed in order to safe guard the onClick event because of the specific implementation. This is history now because I deleted all the relevant Timers and I used some flags instead. So you were correct... :)

I actually started experimenting with KDE dragging in order to understand the behavior in order to replicate it. What I discovered is that dragging is enabled when the user after holding the mouse left click moves the mouse for some pixels around that specific point. So the onClick event in protected by space no time.

The difference in the new implementation is that fixes all the previous issues in responsiveness and hanging in the plasmoid I think. At the same time when the user presses a Window without moving the mouse nothing happens and the application awaits the next steps (releasing which would trigger the onClick event or moving the mouse without releasing so that would be a dragging)

Please test it to take feedback....

Thanks a lot again for the support...

**Comment by MagicMuscleMan** [comment]
So this is a brilliant solution, which works very well according to my tests. Thanks a lot! I now see, that you wanted to overcome the optical glitch when clicking on a window list item as the item would shortly change its appearance without a timer or without your spatial solution. This is great work (btw. I think you were right, as I didn't see the problem, as I thought the window switch would be instantaneously :-))!
