### ISSUE TITLE
Scroll wheel movement between Activities.

### ISSUE THREAD

**Issue by bjwest** [psifidotos/workflow-project#21]
I like the idea of being able to scroll through the activities by just hovering over the icon on the taskbar and using the scroll wheel.  As it stands now, the scroll wheel does nothing while hovering over the icon and quickly being able to scroll though the activities is something I've grown accustom to.  With just two or three running activities, it makes it a bit quicker and easier to switch than having to open the activity monitor and selecting the activity you want.

**Comment by psifidotos** [comment]
Oh, so that's where the scroll wheel was used on the Activities Manager plasmoid... Sounds very interesting actually, I think it's ok for 0.3...

**Comment by bjwest** [comment]
Yes.  Makes it much easier for a quick switch.  Looking forward to 0.3.

**Comment by psifidotos** [comment]
Actually forget it.... I liked it so much that is already in the repo... You can take it now or wait for the official release of 0.2 :)... I used your code in order to understand how to catch the scroll wheel event...

**Comment by bjwest** [comment]
Sweet!  Can't wait, so will grab it now.  It's not my code, I'm just a user of the wheeled activity manager.

**Comment by bjwest** [comment]
Scroll wheel doesn't seem to be working for me.  About says I'm running 0.2.0, but scroll wheel does nothing when hovering over icon.

**Comment by psifidotos** [comment]
if you pulled the latest version and installed it, try to relogin in KDE.
If that's not the case maybe you have only one Activity enabled (it works only with the active activities not the stopped ones) ? In general, you can find me in #workflow-project channel in freenode servers sometimes.

**Comment by bjwest** [comment]
Logging out and in did the trick. Thanks.
