### ISSUE TITLE
Dragging a window sometimes hangs workflow

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#22]
Sometimes, when dragging a window in WorkFlow, the program hangs. The window's name disapperead from the list of open windows on this virtual desktop on the activity and does not appear somewhere else. Instead, the window's icon is shown (larger than usual) in that virtual desktop of the activity without text (like a global window icon, just inside of a virtual desktop).

The program does not do anymore, then. It does not react on further clicks or anything else. This behaviour was tested and observed while WorkFlow is on tha dashboard. Even worse: The task bar and most of plasma stop working when this happens. A relogin fixes the problem until it happens again.

Although this problem is probably hard to debug and not so frequent, it is a grave bug, as it more or less renders the current KDE session useless.

**Comment by dovidhalevi** [comment]
In terminal or Yakuake: killall plasma-desktop;plasma-desktop
will reset.

**Comment by MagicMuscleMan** [comment]
Thanks a lot, dovidhalevi, that helps. So the bug is less critical. On the other hand most users probably do not know these commands (and probably should not know how to use a command line interface) and I guess in the long run the problem will be annoying, anyway.

I just tried and I can trigger the bug quite quickly by just moving a lot of windows around. It seems to be related to some timing issue, but I am not sure about that. It might be related to window grouping, but I am even less sure about that (read: wildly speculating). I am still lacking an idea how to debug this problem. If anyone has an idea, I would be very interested in reading about it.

**Comment by psifidotos** [comment]
I reproduced it. It occurs when you are trying to drag a Window very fast. It must be fixed in the current repo and is going to be ready of course of 0.2. Test it please is order to close the ticket.

**Comment by MagicMuscleMan** [comment]
Even if I am quite late with that, I just wanted to confirm, that this bug is fixed.

**Comment by MagicMuscleMan** [comment]
Even if I am quite late with that, I just wanted to confirm, that this bug is fixed.
