### ISSUE TITLE
Key-shortcut is not saved

### ISSUE THREAD

**Issue by dovidhalevi** [psifidotos/workflow-project#23]
Go to config.
Choose key-shortcut.
Enter one.
Apply, exit.

It is not there.

**Comment by mdaffin** [comment]
**Workaround**
Edit ~/.kde/share/config/plasma-desktop-appletsrc

Find the workflow widget, should be similar to this:

```
[Containments][1][Applets][47]
geometry=20,3,32,32
immutability=1
plugin=workflow # Look for this line
zvalue=0
```

Note down the Applet number ( **47** in the example )

Add the following somewhere in the file (after where the above is located)

```
[Containments][1][Applets][47][Shortcuts]
global=Alt+F1
```

Replace **Alt+F1** with the shortcut you want and **47** with the applet number you found above.

Then restart plasma

```
kquitapp plasma-desktop && sleep 1 && plasma-desktop
```

or logout and back in.

**Comment by mdaffin** [comment]
I cannot see why this does not work as far as I can tell every thing that is needed for this to work has already been done. @psifidotos I suggest you try asking on the #kde-devel or #plasma-desktop freenode irc channels as they know far more then I do about this.
