### ISSUE TITLE
Hide / Delete workspace/desktop Options

### ISSUE THREAD

**Issue by dovidhalevi** [psifidotos/workflow-project#24]
Each workspace might have two icons, a remove [x] and a hide [*] or such.
Remove would delete the workspace. The activity would have one fewer desktops.
Hide would not delete it, just keep it out of the way. Some pager implementation might be needed for this.

ALL deletions should have an "Are you sure -- this cannot be undone" OK/cancel Box.

**Comment by psifidotos** [comment]
I have started to believe that this feature is not so important.... If there arent any clean mockups about the changes that need to be done I think that I am not going to follow that road....
