### ISSUE TITLE
Set Plasmoid icon

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/workflow-project#27]
The plasmoid should provide the possibility to the user to change its icon.

**Comment by mdaffin** [comment]
Given that #31 has a similar idea, to set the icon of the plasmoid to the icon of the current activity would this issue just be adding an unneeded functions?

I cannot see a use case where the user will want to change the icon of the plasmoid that they cannot do by changing the icon of the activity.

**Comment by psifidotos** [comment]
I agree by using the activity 's. Icon and name in the panel we are OK
