### ISSUE TITLE
Reordering Activities

### ISSUE THREAD

**Issue by bmihaila** [psifidotos/workflow-project#30]
It would be nice to be able to change the order of activities as the order is important when using the next-activity global shortcut. At the moment it seems not to be possible in KDE (4.9) as far as I know. So I am not sure if there first needs to exist some support for this in KDE itself before using it in the plasmoid.
Anyways, the feature request is to be able to use drag&drop to reorder activities through the plasmoid as the UI is already promoting this for windows. Maybe at some point even reordering virtual desktops would be useful for the same reason mentioned above.

**Comment by psifidotos** [comment]
I totally agree with you it is already in 0.3 issues. About waiting support in official KDE we can push things a bit  by creating the demand :). Workareas are not supported in KDe yet and many of the functionalities in the plasmoid are hacks. I have the belief that plasmoids can be a very good testing ground in order for the official KDE developers to take ideas for future KDE releases....

**Comment by psifidotos** [comment]
This is almost ready...
Please write ideas about ordering for the UI:
I am thinking about a Dialog that shows a list of all activities
and the user drag n' drops to make the desired order.

Changing activities order in live state without dialog is a lot of pain I think with no reason...
What do you think about the above implementation for the dialog?

**Comment by bmihaila** [comment]
Hi, nice to see all the progress with the bugfixes and refactorings going on. Have tried the current version and found some bugs and wishes that I will write later on more about.

About the reordering. A dialog is ok but I was thinking the most intuitive is to grab&drag the activities in the upper "title bar" where all the activities are shown by name. It might be a bit hidden though and would need mentioning in the help or a popup saying that you can reorder by grab&drag. Additionally one could also reorder the paused activities on the right again by grab&drag.
Depends on what is more work for to implement but from a user perspective I would say I prefer not having extra dialogs with icons or previews when I can do things immediately and live. About how this live moving would behave: either the whole column below the name would move on grab&drag or it would be sliding animated to its position when the title is released somewhere, you can decide what is better.

**Comment by bmihaila** [comment]
![activities-names-bar](https://f.cloud.github.com/assets/2682197/99995/d2e826f0-67dc-11e2-934f-72842741cc1a.png)
Here is what I meant with the activities title bar and the closed activities on the right.

**Comment by bmihaila** [comment]
Oh, ok only now I read your last sentence that it would be difficult to have the live reordering. Well then the dialog is a good solution for now.

**Comment by psifidotos** [comment]
I will give it a try for live ordering just like I did with the window drag n' drop.
It is not the most elegant way to implement it but I think it will do the job.
For the future when the plasmoid goes to QtQuick2.0 I think drag n' drop will be easier to implement...

**Comment by psifidotos** [comment]
BTW, beautiful icons in your activities... :) I feel very happy when people find value in this project....

**Comment by bmihaila** [comment]
Oh, your project is very valuable! Thx a lot again for it.
I use activities since a while and never really liked the awkward and clunky way to move windows between them or have an overview of all my desktops and windows or reorder them ;). So your plasmoid was the solution to a long annoyance and productivity loss :). Was thinking to start solving some of these own problems with a plasmoid but lack of time and the fact that the activities API was still quite in its infancy held me back.
What a nice surprise to find then this plasmoid. The even better thing was that it is a quite good looking plasmoid!
So keep up the good work and design.

**Comment by psifidotos** [comment]
initial alpha support for activities ordering in orderactivities branch... It works but there are some issues with dragging the first activity in each list....

**Comment by bmihaila** [comment]
Wow, nice. Had to give it a try immediately ;) Although it is not so easy to discover at the moment as only grabbing the icon initiates a move. So extending the grab area would be good. Can confirm the issue with the first activity and also cannot always move other activities to the first position. Either they hang and are not displayed (only the grayed out rectangle is displayed) or I just cannot put them to the first position.
Another bug is that even though the activities are reordered in the plasmoid they are not reordered for KDE. If I use the KDE global shortcuts "switch to next activity" the old order is still there.

Anyways, great work, have been waiting for this since I started using activities.
Thx again for the work.

Sorry if I did not open up an own issue for each of the above but guess they are not worth the noise.

**Comment by psifidotos** [comment]
I have uploaded a new version for ordering activities a bit different from the previous one. This is also is orderactivities branch.. Please make it a test to tell me your experience, it is more stable and bug free from the previous one...

About the shortucts... KDE does not support ordering activities at all, so I dont think I can do something until then... :) To go to next or previous activity based on the workflow plasmoid you could use the plasmoid's icon in the panel (scrolling up and down)

**Comment by bmihaila** [comment]
Ok, will give it a test ride immediately.

> About the shortucts... KDE does not support ordering activities at all, so I dont think I can do something until then..

Yes, was afraid that this is the case. Are there any bugs/feature requests open in KDE about that?

> To go to next or previous activity based on the workflow plasmoid you could use the plasmoid's icon in the panel (scrolling up and down)

Yep, I know about that possibility but it is not as "fast" to have to move the mouse there compared to using "win+tab" ... which brings me to my next feature request ;) .... but will open up a new issue for that.

**Comment by bmihaila** [comment]
Ok, my feature request exists already https://github.com/psifidotos/workflow-project/issues/7

**Comment by bmihaila** [comment]
I tried it out and it is very nice, everything works now and it looks good.
Only small issue I could find is that sometimes it takes like 1-2 seconds after dropping the activity before it gets redrawn, so the blue placeholder is visible instead. It mostly happens if waiting a bit before dropping it after grabbing. But I would say it is not a big deal. With yesterday's alpha version I think the bug was that it was not redrawn at all sometimes.

All in all, nice feature. Now it only needs some mentioning in the popup maybe so that people can find it.

Thx again

**Comment by psifidotos** [comment]
I have just uploaded an optimized version in order to be more fluent...
Give a try when you have time... :) I move activities all the time... :)
it is like a game.... :)

Óôéò 31/01/2013 10:26 ìì, ï/ç bmihaila Ýãñáøå:

**Comment by bmihaila** [comment]
Woohaa, fluid and fun. Yep, also played with the reordering for a while cause it now is so fast now. I noticed though that a small hickup happens when you drag the most right one to the most left place (last to be first). But this delay is not that long to be called a bug ;).

**Comment by psifidotos** [comment]
this is merged to tempsync branch...
and considered closed....
