### ISSUE TITLE
Optionally allow the panel icon to display the current activity

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#31]
At the moment there is no easy or quick way to know what activity you are currently on.

You can use the toolbox, but that doesn't always show the activity (if its in a corner) and is hidden by windows, or you can use the activity bar plasmoid which displays all the active activities and takes up allow of space.

It would be nice to be able to configure WorkFlow to display the name of the current activity in place of or next to the icon in when in the panel so that users can at a glance see what activity they are on.

**Comment by psifidotos** [comment]
Oh, that's a nice idea. I track it for 0.3. I think that it is possibly.

**Comment by mdaffin** [comment]
As an extension to this idea, it would be great to have the activity icon used as the icon rather then the static icon.

**Comment by psifidotos** [comment]
that is also a good idea... :)

**Comment by psifidotos** [comment]
Michael, there is a first implementation for this in branch stepto03.
what do you think?

**Comment by mdaffin** [comment]
Not quite there: 
![snapshot1](https://f.cloud.github.com/assets/171232/30473/6a370bc0-4e97-11e2-9dd1-c47bc0dd6df6.png)

Seems there is no image for activities without an image set. (Works when I change the image for an activity)

Also, the name is not readable (probably due to the small size of my panel but this should be taken into account as others will do the same). I think a better layout would be to place the name beside the name at the same size as the taskmanager names (basically like how the task manager displays a task) The name should be optional, not sure if it should default on or off first though.

**Comment by psifidotos** [comment]
The image is fixed or now, but the text needs a lot work so I disabled it.

**Comment by psifidotos** [comment]
For the icons everything is ok now I think. I have also made it optional from the config dialog
