### ISSUE TITLE
Homerun style port

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#34]
I think this application would benefit allot from a port to the way the [homerun](https://projects.kde.org/projects/playground/base/homerun/repository) widget works.

Homerun consists of a separate viewer and widget, where the widget launches the viewer when clicked or activated, this approach might make it easer to implement it as a kwin plugin later. It has a much cleaner implementation and doesn't suffer from some of the bugs of this widget.

There is also the possibility to share code with the homerun widget and/or abstract away some of how it works to make it easier to create full screen widgets in the future as well as maintain this one.

I do see a real benefit to attempting to port the code to homeruns way of doing things and am willing to start/help with the port.

This issue is mostly asking if you are all right with me attempting to do this as I don't have the time to waste if you are not behind it. Feel free to close this issue if you are not willing to back this port.

**Comment by psifidotos** [comment]
James this is not bad idea at all but before proceeding one question: With this way we forget PopUp right?Is it going to work only in fullscreen? Or will it be possible to remember possition and size for the viewer?

**Comment by mdaffin** [comment]
> With this way we forget PopUp right?

Not sure what you mean by this, the widget will not be a popup widget in code, but should effectively function like one.

> Is it going to work only in fullscreen? Or will it be possible to remember possition and size for the viewer?

I have not found the part of the code that makes the app full screen, but it is just an application so I do not see why this would not be possible. The difficult part will be position and sizing if there are multiple widgets placed given only one instance of the application can run at a time.

Another disadvantage will be that the widget will only be an icon if placed on the desktop, but we might be able to work around this later (possibly reimplement the popup style if the widget is not set to full screen).

This will be allot of work, I suggest we set this as a possible feature for the 1.x branch or later once we have it working, keeping it in an experimental branch until then and keep up maintaining the 0.x branch for now.

**Comment by psifidotos** [comment]
Ok, James it looks promising but I can not be sure yet. You see I dont have much time this period of my life. The priorities for the application for me are a bit different until version 0.3 . I want to clean the code a lot. There are a lot of parts that have been programmed in a rush during the last summer. Version 0.3 will have a much cleaner implementation especially for the logic parts. For example creating a workareas data engine, remove all the hard hacks from inside the code and put them in separate classes, changing the parameters handling (create a class which is going to load all the parameters and can be accessed from the QML part directly) etc.

For some of the requested improvements that many users have asked for, I will try to make them available in 0.3 but I dont think that 0.3 is going to be available any time soon.

I believe that we must wait until version 0.3 to decide if we want such an improvement like this one mentioned. There are good points but big changes will have to be made also. I dont say no in an experimental branch that will try such an implementation but I can not promise you that I can help or that it will be definitely added in future versions.

On the other hand I would love to have some help in the development process....

**Comment by mdaffin** [comment]
I have started to port the widget (already have the launcher done) and having a deeper look at the viewer I have found where it sets the size so it will be possible to make it launch as a normal sized window. I think it will also be possible to make the launcher tell the viewer where and how big it should show so each launch should be able to position it independently. Although I am not sure about it telling the launcher how big it was when it closed... but I don't think it is impossible.

My progress will be in my homerun-port branch. So far it has not touched the existing code (except the CMakeLists.txt file).

**Comment by psifidotos** [comment]
ok perfect james...

**Comment by mdaffin** [comment]
Ok, the basic viewer and widget are working. The next step is to get the qml code to properly work given that I have not yet exposed anything to the qml code like you do in your widget.

Before I attempt to port your code into the viewer I was wondering if you would consider another style import from the way homerun works (see below), this would benefit both your code and mine so I would do it in a separate branch and get it merged in with your master before I continue on the launcher/viewer port.

The container class in homerun is a very basic container that simply create a declarative context sets it up and displays it as well as handles anything only relevant to the container (see fullview.{h,cpp} if you want to see the code). Then the qml code manages its contents with the help of c++ declarative plugins that are installed separately and imported into the qml code. This makes the qml code self contained and much more portable as you no longer have to implement all the bridges between the c++ and qml in the container widget to get the qml code to work.

This also makes it easier to develop new plugins for the system to expand upon it later. It also has the advantage of less memory usage if they use multiple widgets as they can share the components library.

Proposed changes to the source structure:
components/ - Contains the core qml components, anything that can be reused as well as c++ plugins to the declarative system (currently some of the classes in src/)
package/ - Contains the core qml code the displays the widget (currently what's in src/package)
widget/  - The applet specific code (currently what's in src/)

This will require large amounts of changes, but I think once done it will give a cleaner layout. This is also an opportunity to look at the code and clean it up and fix some bugs.

If you are ok with this then I will open a new branch to start work on it.

Sorry I keep mentioning how the homerun widget works, but the more I look at it the nicer its implementation look to me and it seems to be a very good example to follow of how to write a qml/c++ widget.

**Comment by psifidotos** [comment]
james this is radical. I definitely can not support until 0.3. There are many things to be done until then and such a huge change would require time to learn the code from the begin. Of course you can create a new branch to test all of it but I cant support it until version 0.3

**Comment by mdaffin** [comment]
I don't mean for you to drop development towards 0.3, just keeping you informed of my development and looking for your backing that you might pull these changes once they are ready.

I have create a new branch and pushed the restructured code + an the start to the components plugin but the rest is largely going to involve rewriting how the qml works as well as the activitymanager and taskmanager as these are currently very tightly coupled and might be more work trying to uncouple them.

**Comment by psifidotos** [comment]
Ok james, that's perfect with me...

**Comment by mdaffin** [comment]
I have been going through some of the qml files and tidying them up, I have come across one element that I cannot figure out what it is for: ActivityDeleg.fadeIcon

As far as I can tell it is placed over the activity icons and is the same color as the background. So is there any point to it being there?

**Comment by mdaffin** [comment]
Ahh, I found why it is there :)
