### ISSUE TITLE
The zoom bar is not shown correctly

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#4]
The zoom bar in the lower right corner is not fully shown. The minus and the plus zoom symbols are shown as is the circle which shows the current zoom level. The circle can be moved to the left and to the right, which results in correct zooming. However, the bar itself (normally drawn in blue and grey color) is not shown. It is shown when creating a new user account (probably due to the empty user profile), but not for my normal account.

**Comment by psifidotos** [comment]
The zoom bar, is a PlasmaComponent. I had this issue in the past. I think that it is the spescfic Plasma theme you use. Try using the Oxygen Plasma theme and make a relogin to test it.

**Comment by MagicMuscleMan** [comment]
Using the Oxygen theme and relogin did not change anything. I do not think, that the theme really gets changed, as I cannot spot any difference.
