### ISSUE TITLE
One line if statements

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#45]
What is your preference on one line if statements?

1) 

```
if (condition) statement;
```

2)

```
if (condition)
    statement;
```

3)

```
if (condition) {
    statement;
}
```

Just so I know which to use when re-factoring the code as I find it is best to keep to one style. 

PS: I know this isn't really an issue, but there is no other way to discuss things like this on github

**Comment by psifidotos** [comment]
No problem at all,

I usually use the second (2)
