### ISSUE TITLE
Changing activity symbols does not work

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#5]
When a symbol of an activity is to be changed, it can be selected, but after choosing the symbol, the symbol does not get updated, but stays the same (the mainly yellow plasma cashew).

**Comment by psifidotos** [comment]
I have the same problem in my system. This is not WorkFlow issue but KDE's. You probably use KDE 4.8, programmers said that in 4.9 it is going to be fixed. In order to test it,you shouldnt  also been able to change an activity's icon from the official activities bar.

**Comment by MagicMuscleMan** [comment]
Yes, I use KDE 4.8 and it does not work in the official activities bar, too. I tested it in a pre-release version of 4.9 and it didn't work in the official bar either. But I do not know how large the gap between that pre-release and the final 4.9 is. I could not find a live CD with the KDE 4.9, otherwise I had tested it there.

**Comment by bjwest** [comment]
Still broken in KDE 4.9.. :(

**Comment by psifidotos** [comment]
In KDE 4.8 suddenly it worked again.... Icons are stored through Nepomuk so, all this time I had enabled Nepomuk but not Strigi. By enabling Strigi again after all this time that was inactive, icons can be changed again... I dont know if that is going to remain will see... So definitely icons need nepomuk and strigi active. 
From KDE Control Center -> Desktop Search,  you must check both
-- Enable Nepomuk Semantic Desktop
-- Enable Nepomuk File Indexer

--Enable Email Indexer (you do no have to enable this one)

Of course I dont know in your system but Nepomuk and Strigi in my system some times make the whole experience unresponsive, we will see....

**Comment by bjwest** [comment]
Interesting.  Thank you for this.  I'll have to file a bug report with KDE about this.  I see no reason to have Nepomuk File Indexer enabled to be able to change the activities icon.

**Comment by MagicMuscleMan** [comment]
I have both enables in the control center and it does not work for me. On the other hand, I think that I once disabled strigi somewhere in a configuration file, but I am not sure about that.

**Comment by psifidotos** [comment]
does this still remains?

**Comment by psifidotos** [comment]
probably we are ok with this...

**Comment by MagicMuscleMan** [comment]
It's still in issue in 4.8. But as more recent versions of workflow-project do not seem to work on 4.8 anyway, that wouldn't be an issue as long as it works with KDE 4.9 and higher.

**Comment by psifidotos** [comment]
> It's still in issue in 4.8. But as more recent versions of 
> workflow-project do not seem to work on 4.8 anyway, that wouldn't be 
> an issue as long as it works with KDE 4.9 and higher.
> 
> In 4.8 setting activity's icons was mainly through Nepomuk, in 4.9 the 
> situation improved but in the beginning the old configuration was 
> creating conflicts. In 4.10 I think that Nepomuk is not a requirement 
> for the Activities icons.

To mention here that WorkFlow 0.4.0 will be the last to support Plasma 
Desktop 4.9. Next version 0.5 will use probably Plasma Desktop 4.10 in 
order to support features that dont exist before that.
For example:
1) Presenting Activities linked documents (Linked, Recent, ...) through 
the available qml models

2) drop the Window that was showing the window previews for a specific 
Desktop and try to use
a "Present Windows" way to show them. This way more space will be used 
meaning bigger
Previews :) and probably a search filter for them also like in "Present 
Windows"

**Comment by MagicMuscleMan** [comment]
That sounds very promising, thanks for your great work! I am looking forward to test recent versions as soon as my distribution has a more up-to-date KDE included.
By the way, it think it would be a great thing if there were a table somewhere on the homepage where the minimum required KDE version is listed for each workflow release.

**Comment by psifidotos** [comment]
> By the way, it think it would be a great thing if there were a table 
> somewhere on the homepage where the minimum required KDE version is 
> listed for each workflow release.
> 
> I have just added it in the Installation page in the wiki...

**Comment by MagicMuscleMan** [comment]
Thanks a lot, that will be very useful in the future!
