### ISSUE TITLE
Scale only the desktop previews

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#52]
Is there a need to scale all of the elements? I find that at both the larger and smaller ends this makes the widget look off. 

I suggest changing the scaling to only scale key areas such as the desktop previews (and thus the width of each activity).

With less to scale the animations should also be smoother.

I am in two minds about the stopped activities also scaling, but I think a better solution to this is to make the panel resize on dragging the panel handle and the elements inside it to resize with this.

**Comment by psifidotos** [comment]
this is not needed any more.... Zooming is smooth in new versions...
