### ISSUE TITLE
Animations in the about dialog and tour take to long to complete

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#56]
The animations should be finished in less then a second, preferably in the same time as all other animations finish. As it currently stands you have to wait a few seconds until all the information is shown.

I also have to ask if all these animations are needed? I think it would be better to reduce the animations as much as possible and only leave in the ones that fee natural. As simple as they are to create, and as interesting they can be you have to make sure they do not get in the way of the program and make sure they do not make the program look unprofessional.

**Comment by psifidotos** [comment]
I can remove them. I added them in order to make the user read the Tour....
Reducing Animation Time is ok with me...

**Comment by mdaffin** [comment]
Currently for me it just slows me down if I try to read it, and distracts me from the actual content. Flashy animations can look nice, but they do often just slow down the user which often you don't want to do. Nothing is more annoying then having to read slower then you are comfortable with. Not to mention that some of the animations are buggy (the scrolling text displays the styling characters until the style is fully written which looks very odd).
