### ISSUE TITLE
Make use of the official toolbar component

### ISSUE THREAD

**Issue by mdaffin** [psifidotos/workflow-project#59]
There are currently several bugs with the toolbar implmentation. Rather the fixing these and basically duplicating the code that already exists it would be better to make use of the official toolbar components like in my dataengine-port branch. It makes the interface more consistent and looks better.

In addition to this it would be nice if the locked icon switched to the unlocked icon when the widgets are unlocked.

**Comment by psifidotos** [comment]
I tried your version Michael but I dont like the default Toolbar appearance(for the buttons)... 
What works ok for me, is to use the PlasmaComponents.Toolbar only for the background and all the other buttons to remain as it is (I dont like only the HelpButton)
For the lock unlock icon I hadnt found at all the relevant icon reference...
