### ISSUE TITLE
Changing order of activities

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#6]
Activities seem to have some random order, which is not optimum, either because its more logical to have the default activity (if one has one) most left (or at the top) when having a left-to-right native language or because similar activities should be placed next to each other. This is true for both lists, i.e. the active activities and the paused activities.

A simple possibility might be to use drag-and-drop on the activity names similar to tab-rearrangement in Dolphin. Ideally the order information should be stored to survive a reboot and a pausing/starting of the activity.

As an extension it could be possible to stop an active activity by dragging it to the list of paused activities and vice versa. This last idea might be a good idea or not, I just wanted to mention it for completeness.

**Comment by psifidotos** [comment]
This has been scheduled also for 0.3 but I dont know if it's going to be with live dragging. It must be tested but there is a case that a dialog is shown with all Activities List and by dragging you set their order.

**Comment by psifidotos** [comment]
This is almost ready...
Please write ideas about ordering for the UI:
I am thinking about a Dialog that shows a list of all activities
and the user drag n' drops to make the desired order.

Changing activities order in live state without dialog is a lot of pain I think with no reason...
What do you think about the above implementation for the dialog?

**Comment by psifidotos** [comment]
initial alpha support for activities ordering in orderactivities branch... It works but there are some issues with dragging the first activity in each list....
