### ISSUE TITLE
Installer does not set correct access rights for directories

### ISSUE THREAD

**Issue by bmihaila** [psifidotos/workflow-project#63]
Hi

The installer does not set the access right for "others" for the $kdedir/apps/plasma/plasmoids/workflow and /usr/lib/kde4/imports/org/kde/workflow . They are set to --- i.e. others cannot access the directory, which leads to an error message when starting the plasmoid about "package components not found" and the plasmoid not being loaded. The access rights should be "r-x" for "others".

**Comment by psifidotos** [comment]
that is strange....

can you trace it down why or what can change in the install.sh file?

**Comment by bmihaila** [comment]
Hi

I was first thinking that it might be something about my umask setting for root but that is the default one, although the one for my user is different. I will try to investigate a bit more into it as I did not have any problems with other cmake scripts and it seems that all the other directories are ok but only the ones above are not world readable.
Ok, I found a reeeally old bug about cmake installs and umask from 2006.
As soon as I find some more time I will test it with a different umask and see if there is general solution to it and where the bug is.

**Comment by mdaffin** [comment]
This is not an issue with the install.sh, if anything it is an issue with the build system. However I find it more likely to be a problem with your computers setup then the build system as we just use the cmakes install command to install the files.

Can you show us the output of `ls -al /usr/lib/kde4/imports/org/kde/workflow` and other folders in question. Also, what is your umask set to? And what permissions does a file get if you create one in the mentioned directories (`export file=/usr/lib/kde4/imports/org/kde/workflow/test.file; sudo touch $file; ls -la $file; sudo rm $file`)?

**Comment by psifidotos** [comment]
can this be closed?

**Comment by bmihaila** [comment]
Yes, I will close the issue. It seems to be about the umask. Did not know that sudo uses the umask from the user and not the superuser. It seemed weird that only the toplevel directory (workflow) was having the "wrong" access rights but I guess I should look into cmake if one has to set the rights in the cmake file.
