### ISSUE TITLE
Drop window artefact

### ISSUE THREAD

**Issue by bmihaila** [psifidotos/workflow-project#65]
Hi

Using the tmpsync branch I came across a bug. When dropping a window on the "+" symbol that would add another desktop the window remains there as can be seen in the attached image and cannot be moved away or closed or anything. It just hangs there. Even closing the desktop it should be on does nothing. Only after moving another window the frozen one gets "released" and can now be interacted on in the plasmoid.
![window-artefact](https://f.cloud.github.com/assets/2682197/120862/37ed8a26-6d47-11e2-879f-ce30c668a33a.png)

**Comment by psifidotos** [comment]
That issue is not appearing in my version... I made a clean uninstall , install to be sure... Does that remain in that case?

**Comment by bmihaila** [comment]
Just tried out master again and it is still there. This is what plasma says when it happens:
`file:///usr/share/kde4/apps/plasma/plasmoids/workflow/contents/ui/DraggingInterfaceTasks.qml:269: TypeError: Result of expression 'viewXY' [undefined] is not an object.`
So again, it happens when I drag a window on the "+" and drop it there. Then a new desktop is opened but the window itself is in a frozen state and looks like in the picture. Additionally I cannot drag the plasmoid background to scroll but I can zoom and start/stop activities and so on. Everything is fine again after dragging&dropping another window. Tried it with activities locked/unlocked and with/without everywhere windows panel.
