### ISSUE TITLE
Keyboard navigation

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#7]
If WorkFlow is configured to appear on the dashboard and there is a shortcut to open the dashboard, in theory it would be possible to navigate through activities and their virtual desktop just by using the keyboard. Unfortunately, this does not seem to be supported, right now.

I propose that the left arrow and the right arrow select the left and the right activity (relative to the active activity), respectively. If the newly selected activity has the same number of virtual desktops or more, the virtual desktop with the same number should be selected (i.e. going horizontally in the virtual desktop/activity matrix). If the newly selected activity has less virtual desktop than the number of the virtual desktop selected before, the virtual desktop with the highest number should be selected, but the higher number should be remembered and reused, if another activity is selected which again has more virtual desktops. This should work as the character selection when scrolling through lines in kwrite, just rotated by 90° (the characters being virtual desktops, the lines being activities). It probably makes sense to have cyclic behaviour selecting the most right activity if the most left activity has been active before and the left key has been pressed. The top and bottom arrows should change the virtual desktop, also with a cyclic behaviour.

As the activities and virtual desktops now can be changed by using the keyboard, it probably makes sense to also allow selecting a virtual desktop of an activity by using the keyboard. As the enter key and the space key normally are used to press a button when using the keyboard, it would be great if both keys could be used to close the dashboard in this case ending with the selected virtual desktop/activity.

**Comment by psifidotos** [comment]
This is interesting but it must be tested. I think that it must be created a WorkArea's selection mechanism just like when dragging a window in order to select a Workarea and then with Enter for example to activate it if you want.

**Comment by mdaffin** [comment]
ListViews already have a selection mechanism, it would be worth making use of it. I was going to look into adding keyboard functionally at some point after I finish the data engine port.

Here is my idea for it:
left/right - move selection of activity left/right
up/down - move selection of virtual desktop up/down
enter - switch to select activity and desktop
space - rename current activity/desktop

Default to selecting the current virtual desktop for that activity (if kde supports this, which I think it might in 4.9 or 4.10) else the same virtual desktop for the current activity. Selection can wrap around the edges.

**Comment by psifidotos** [comment]
yes, this looks perfect, I was thinking the same, I would add only the activating the stopped activities also.

**Comment by mdaffin** [comment]
enter to activate/switch to and backspace to stop?

**Comment by psifidotos** [comment]
No, Enter to activate/swith to/stop. When the user is in the last active activity with right arrow can access the stopped activities listview. When the user  is at the stopped activities list view with a left arrow can return to active activities.

**Comment by mdaffin** [comment]
I think using Enter to activate and stop the plasmoid would be confusing and could lead to people accidently stopping a activity when they meant to switch to it. It also means you cannot stop a plasmoid that is not activte

**Comment by psifidotos** [comment]
For stopping an active activity I agree (we could use another key, e.g backspace) . But I think it could be very good to activate activities from the stopped activities panel.

**Comment by mdaffin** [comment]
> For stopping an active activity I agree (we could use another key, e.g backspace) . But I think it could be very good to activate activities from the stopped activities panel.

I agree with this :)

**Comment by MagicMuscleMan** [comment]
When you are at it, please do not forget to add vim key navigation, too, as it is very useful to not have to move the hands at all (otherwise you could use the mouse, couldn't you?). So please add ("h" = "left", "j" = "downwards", "k" = "upwards", "l" = "right" (where the latter one is an "L"). For stopping an activity, there is also a "break" key (http://en.wikipedia.org/wiki/Break_key), which should be supported as well.

If possible, it would be great if the keyboard navigation could be realized by using shortcuts. Ideally, they could be configured by users as in most other KDE applications.

**Comment by mdaffin** [comment]
> please do not forget to add vim key navigation, too

I was considering this as well :) given that some of the other kde applications support vi shortcuts (okular comes to mind) I dont see why not.

> If possible, it would be great if the keyboard navigation could be realized by using shortcuts. Ideally, they could be configured by users as in most other KDE applications.

This would also be nice, but at the same time I wouldn't want to make the configuration overly complicated for basic navigation. (especially if you get it right, then 99.9% of people wont want to change it). Might be better to have a config that people can edit if they want to change them that way the option is there but wont clutter up the settings to much. Just an idea.

**Comment by psifidotos** [comment]
The days for this are coming... :) I will make first the KWIn features requests and then take care of this one... :)
Just to add in the discussion... There are two keyboard navigations.... One is inside the plasmoid which has already described but the second could be to add Extra Global Shorcuts for example (Next activity, Previous Activity - according to plasmoid's activities orders) . I have seen some articles in blogs about the second but I must dig them out... :) I have started to believe that many KDE users use the keyboard extensively... :) so, we must try to do our best in this....

**Comment by psifidotos** [comment]
Ok.... There is work for this in the keynavigation branch... I think I can be considered beta and not alpha.... It actually most of the features have been implemented....

**Comment by bmihaila** [comment]
Great thing again. About the global shortcuts I think you mean these blog posts:
http://kdeblog.mageprojects.com/2012/11/28/application-wide-shortcuts-using-qshortcut-in-qml/
http://kdeblog.mageprojects.com/2012/12/07/application-wide-shortcuts-in-qml-this-time-without-qshortcut/

It would be of course nice to have some global shortcut then the reordered activities could be switched to by using your plasmoid and not the KDE ones which are quite behind feature wise.

**Comment by psifidotos** [comment]
this is ready in the master...

**Comment by psifidotos** [comment]
I am afraid that the above examples are only application wide and not global shortcuts. But I am not sure....

**Comment by bmihaila** [comment]
Yep I think they are only application wide, pity.

Something else. Would it be possible to navigate inside a workarea through the windows?
At the moment the arrow keys can be used to navigate the workareas but it would be nice to also select a window inside a workarea. The use cases would be: 
1. activate selected window with enter, i.e. go to that workarea with the window on top
2. move selected window to other workarea, i.e. the arrow keys would move the window to the workarea to the right, left, down and so on. Maybe using shift+arrow key would be wiser and less confusing with the "move to right, left ... workarea" normal functionality of the arrow keys

Don't know how it would be best to implement the navigate windows, here some ideas:
1. use tab to cycle through the windows while highlighting the currently chosen
2. use a special key to snap the arrow keys inside the workarea to use them to navigate through the windows

I think the first thing with tab is better and also the shift-arrow keys for moving.

What do you think?

**Comment by psifidotos** [comment]
It's a little too much for next version...
I would prefer to think it for the next big release and after there is a lot of testing in keyboard behaviors...

**Comment by bmihaila** [comment]
No problem. It was more like the start of a discussion for what could be next to keyboard navigation.
So lets come back to it when there is time after finishing current version's issues.
