### ISSUE TITLE
Global Shortcuts Plugin

### ISSUE THREAD

**Issue by psifidotos** [psifidotos/workflow-project#70]
I think I found a way to implement this... :)
the kactivities library uses the plugin system in order to register global shortcuts...
I can use the same approach i think... :)

**Comment by psifidotos** [comment]
When I was thinking that this does not work, I show the shortcuts references in the Plasma Shell group in global shortcuts. References are, WorkFlow: Next Activity, WorkFlow: Previous Activity

**Comment by psifidotos** [comment]
I forget you need a relogin for this as these shortcuts are from the data engine.

**Comment by bmihaila** [comment]
Wohaa, works like a charm. Finally KDE activities can be reordered and cycled through in that order.
Thx a lot :)
Think you can close the issue.

BTW: you don't need to re-login but just restart plasma

**Comment by psifidotos** [comment]
When I merge development to master this issue will be closed automatically...

About the re-login, I dont use the term restart plasma because users are easily confused.
I usually say, relogin (log out - in) and restart(restart your computer)
