### ISSUE TITLE
Window previews button disabled

### ISSUE THREAD

**Issue by bmihaila** [psifidotos/workflow-project#75]
Hi

When using the kwin script of this plasmoid and enabling there the window previews somehow the button to enable disable window previews in the plasmoid is not working anymore. That means the button remains in disabled state and cannot be toggled to enabled again. The button in the kwin script is still usable but the one in the plasmoid seems broken. The button is ok again after disabling the kwin script and restarting plasma+kwin.

**Comment by psifidotos** [comment]
I can not reproduce that one...

The window previews button can be disabled only when there are no desktop effects enabled or the user has disabled them for performance issues.

**Comment by bmihaila** [comment]
Hi

Could not reproduce again. Might have disappeared with reinstallation etc. Will close it.
