### ISSUE TITLE
Removing a virtual desktop does not really remove it

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#8]
If there are, for example, two virtual desktops in an activity. Now, the second virtual desktop of the activity gets deleted in WorkFlow. It then cannot be selected anymore from WorkFlow. However, it still can be selected using the general KWin keyboard shortcut or the virtual desktop selectioni widget. In other words, the desktop does not get deleted, but only hidden in WorkFlow, which is not what a user expects, as a user expects a consistent number of virtual desktops in an activity across all tools.

**Comment by psifidotos** [comment]
This is KDE related. Desktops are not unique per Activity. The number of desktops is the same for all Activities. If you set 3 desktops for example, all Activities will have 3 desktops. In current implementation the WorkFlow just hides the rest desktops if not needed. I believe that if there is user base which wants that, the KDE Developers could be persuaded about a way to implement it. I tried in the past to ask them but there is not a developer which would like to develop Virtual Desktops more that the current implementation.

WorkFlow is also an effort to investigate the user needs and create a link between users workflow needs with Plasma developers and their fantastic new technologies in KDE Plasma

**Comment by MagicMuscleMan** [comment]
Thanks for clarifying. I think when WorkFlow is more mature, users will find it obvious, that different tasks need a different number of virtual desktops. I am positive, that the developers will understand. If there is no volunteer, we maybe need to look at the code ourselves. Probably they accept the patch if it does not change the behaviour with the official activities panel.

**Comment by mdaffin** [comment]
Considering that this is not supported in kde, I wonder if its better to rename the delete workspace button to hide workspace (as mentioned in issue #24). This give a more accurate depiction as to what is actually happening. Might also be worth adding an unhide button or showall button.

If/when the ability to change the number of desktops per activity gets implemented in kde then it would be a good idea to implement a delete function as well.

**Comment by MagicMuscleMan** [comment]
This is an idea, which might be worth implementing.
Another idea might be to deactivate that functionality completely until the variable number of virtual desktops per activity is there. The last thing is not even sure, as it might be that the long term idea of using KDE is using one virtual desktop per activity (possibly with grouping activities to activity groups, note: I am just guessing here). Is the hiding/deleting of a virtual desktop really used, given that is has to be done on every log-in?

**Comment by psifidotos** [comment]
Well for this soon I will try an implementation soon...
The structure will be the following: 
Two modes:Active(Current implementation) / Passive(Clean Virtual Desktops experience)
For Active no changes,
For Passive,
- Same number of workareas for all Activities.
- Workareas can be hidden/unhidden (not closed)
- Add Workareas buttons are hidden. A new global button for
  adding desktops and one for removing them appears under
  all Workareas.

How do you find it?

**Comment by psifidotos** [comment]
I have started to believe that this feature is not so important.... If there arent any clean mockups about the changes that need to be done I think that I am not going to follow that road....

**Comment by MagicMuscleMan** [comment]
Sorry for not commenting for such a long time. I also do not think, that this feature is so important. The current state is a bit unclean, but it is not urgent, so it can be done when someone cares enough about that feature to do it.

**Comment by psifidotos** [comment]
> Sorry for not commenting for such a long time. I also do not think, 
> that this feature is so important. The current state is a bit unclean, 
> but it is not urgent, so it can be done when someone cares enough 
> about that feature to do it.
> 
> I totally agree. The situation has also been improved with version 0.4.0 
> because Workareas do not force Virtual Desktop settings, so the user can 
> add/removed VDs from the pager or anything relevant.
