### ISSUE TITLE
Typo in Original Translation String

### ISSUE THREAD

**Issue by rodrigoesborges** [psifidotos/workflow-project#80]
In string "Let's see how the previous mentioned example... " instead of available, we see avaible. I couldn't fix it myself.

**Comment by psifidotos** [comment]
this is updated...
dont worry, the source strings can only change through the application's source code..
So for any errors you find, just report them and I will fix them... :)

**Comment by rodrigoesborges** [comment]
Not worried, just wanted to register it here before I would forget. Keep the great work!
