### ISSUE TITLE
'Edit Workarea' option has incorrect icon

### ISSUE THREAD

**Issue by ThatAnnoyingCatAt4am** [psifidotos/workflow-project#82]
As it shows on screenshot, 'Edit Workarea' option near virtual desktop has incorrect icon.
![screenshot-015](https://f.cloud.github.com/assets/1220155/347195/10732a9a-9ea8-11e2-824b-6a56d18de55d.png)

**Comment by psifidotos** [comment]
Hello..

What is probably happening is that you are not using the Oxygen icon theme.
the icon that should exist is "im-status-message-edit".

If you want to keep your icon theme then you can hand write directly what icon would you like to be used (inside the installed qml code).

After a simple relogin everything is going to be fine....

**Comment by ThatAnnoyingCatAt4am** [comment]
Thanks for your answer. Turns out, the icon was missing because I didn't have kopete installed.
