### ISSUE TITLE
Selecting an activity without selecting a virtual desktop

### ISSUE THREAD

**Issue by MagicMuscleMan** [psifidotos/workflow-project#9]
It would be great if it were possible to select an activity without selecting a virtual desktop in that activity. The use case is the following. Assume I have an activity with two virtual desktops. Now work gets interrupted and another activity is used. After the interruption is finished, you want to switch back to the original activity, but might have forgotten on which virtual desktop you have been. If the activity could be selected instead, it could just activate the virtual desktop which is the most recently active virtual desktop of that activity.

This is similar to what kwin does. When cycling through the activities (using META+TAB as default), the used virtual desktop of each activity gets remembered, so this information must be already available somewhere. It could be implemented, that klicking on the activity name or the activity symbol in WorkFlow activates that activity with the corresponding virtual desktop.

**Comment by psifidotos** [comment]
This is also very good. You gave me understand a talk around that in plasma-devel mailing lists. You are so right. This is the current implementation of Activities in Plasma actually. I am only thinking what is going to be the event to activate that behavior. What do you think if clicking the icon activates the Activity and Double Clicking changes the icon. I do not want to add new buttons in Activities Editing State because it will create clutter(only if I it is a very important new feature for example supporting the new Activities Documents technology)

**Comment by MagicMuscleMan** [comment]
When the activities are locked, the decision is simple. Just use the whole area of the name, the symbol and the background (without the pause button).

This solution would already fit my needs, as I most of the time have the activities locked so that I do not accidently delete an activity. Additionaly, the name and the symbol are only changed rarely.
But if you want to support activating an activity when activities are unlocked, I would recommend changing the name only if the user clicks on the pencil next to the name. Otherwise the activity should be selected with the obvious exceptions of the symbol name, and the four buttons. As the pencil and the name can overlap at the moment, the pencil must have a higher priority (being in the foreground?) relative to the name.

I wouldn't use double clicking, although I agree it is tempting, as it is not used for changing in KDE anywhere else as far as I know (even in Gnome and Windows the logic is quite the other way round: single click: change/rename, double click: execute/activate). I could also imagine a right click with a context menu for the desktop, but I do not know if that is possible, as it might be problematic on tablets.

**Comment by psifidotos** [comment]
I have imported the following behavior in master. Clicking an activity name activates it, double clicking editing. For the pencil icon I have to think it a bit...

**Comment by MagicMuscleMan** [comment]
I can confirm, that it works. Thanks a lot for implementing.

As said, the pencil is not important to me, I just thought that it would improve consistency. I am completely fine with the change you did and you might close this issue.
